Collections:
- Metadata:
    Architecture:
    - Alias-Free Generative Adversarial Networks (NeurIPS'2021)
  Name: Alias-Free Generative Adversarial Networks (NeurIPS'2021)
  Paper: []
  README: configs/styleganv3/README.md
Models:
- Config: configs/styleganv3/stylegan3_t_afhqv2_512_b4x8_official.py
  In Collection: Alias-Free Generative Adversarial Networks (NeurIPS'2021)
  Metadata:
    Training Data: Others
  Name: stylegan3_512
  Results:
  - Dataset: Others
    Metrics:
      Comment: official weight
      EQ-R: 13.51
      EQ-T: 60.15
      FID50k: 4.04
    Task: Unconditional GANs
  Weights: https://openmmlab-share.oss-cn-hangzhou.aliyuncs.com/mmgen/stylegan3/stylegan3_t_afhqv2_512_b4x8_cvt_official.pkl
- Config: configs/styleganv3/stylegan3_t_ffhqu_256_b4x8_official.py
  In Collection: Alias-Free Generative Adversarial Networks (NeurIPS'2021)
  Metadata:
    Training Data: FFHQ
  Name: stylegan3_t
  Results:
  - Dataset: FFHQ
    Metrics:
      Comment: official weight
      EQ-R: 13.12
      EQ-T: 63.01
      FID50k: 4.62
    Task: Unconditional GANs
  Weights: https://openmmlab-share.oss-cn-hangzhou.aliyuncs.com/mmgen/stylegan3/stylegan3_t_ffhqu_256_b4x8_cvt_official.pkl
- Config: configs/styleganv3/stylegan3_r_afhqv2_512_b4x8_official.py
  In Collection: Alias-Free Generative Adversarial Networks (NeurIPS'2021)
  Metadata:
    Training Data: Others
  Name: stylegan3_afhqv2
  Results:
  - Dataset: Others
    Metrics:
      Comment: official weight
      EQ-R: 40.34
      EQ-T: 64.89
      FID50k: 4.4
    Task: Unconditional GANs
  Weights: https://openmmlab-share.oss-cn-hangzhou.aliyuncs.com/mmgen/stylegan3/stylegan3_r_afhqv2_512_b4x8_cvt_official.pkl
- Config: configs/styleganv3/stylegan3_r_ffhqu_256_b4x8_official.py
  In Collection: Alias-Free Generative Adversarial Networks (NeurIPS'2021)
  Metadata:
    Training Data: FFHQ
  Name: stylegan3_r
  Results:
  - Dataset: FFHQ
    Metrics:
      Comment: official weight
      EQ-R: 40.48
      EQ-T: 66.65
      FID50k: 4.5
    Task: Unconditional GANs
  Weights: https://openmmlab-share.oss-cn-hangzhou.aliyuncs.com/mmgen/stylegan3/stylegan3_r_ffhqu_256_b4x8_cvt_official.pkl
